# @Author: Daniel Gangl
# @Date:   2021-07-20 09:07:31
# @Last Modified by:   Daniel Gangl
# @Last Modified time: 2021-07-20 10:38:44
version: "3"

services:
  iobroker:
    build: ./iobroker
    container_name: iobroker-cybro
    hostname: iobroker-cybro
    # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
    expose:
      - 8081
    volumes:
      - ..:/workspace:cached
      - iobrokerdata-cybro:/opt/iobroker
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - TZ=Europe/Berlin
      - SETGID=1000

  # Reverse proxy to load up-to-date admin sources from the repo
  nginx:
    image: nginx:latest
    depends_on:
      - iobroker
    links:
      - iobroker
    container_name: nginx-cybro
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ..:/workspace:cached
    ports:
      # Make the ioBroker admin available under http://localhost:8082
      - 8081:80

volumes:
  iobrokerdata-cybro:
